services:
  news-site:
    container_name: news-site
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - ./app:/app:Z
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - my_network
    # command: sh -c "npx prisma migrate dev && --name init npm run dev"

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - my_network
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
    #   interval: 10s
    #   retries: 5
    #   start_period: 30s
    #   timeout: 10s
    
  reverse-proxy:
    image: nginx:1.23.0-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
    - news-site
    networks:
      - my_network
    restart: always

networks:
  my_network: